<%-- 
    Document   : register
    Created on : 06 20, 21, 6:54:20 PM
    Author     : Kirby Wenceslao
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Register Here</title>
    </head>
    <body>
        <h1>Dito ka magreregister ./.</h1>
         <form>
            <label>Personal Details</label><br>
            <hr><br>
            <label>First Name</label><br>
            <input type ='text' placeholder = "enter first name here"><br>
            
            <label>Last Name</label><br>
            <input type ='text' placeholder = "enter last name here"><br>
            
            <label>Contact Number</label><br>
            <input type ='number' placeholder = "enter contact number here"><br><br>
            
            <label>Your card number and password would be auto generated by the system</label><br>
            <input type ='submit' placeholder = "REGISTER"><br>
         
        </form>
        <a href ='Index'>Go Back!</a>
    </body>
</html>
